#!/usr/bin/env bash
# discover-claude-context.sh — Auto-discover workspace context files and write
# CLAUDE.md for Claude Code session context loading.
#
# Invoked as a Claude Code SessionStart hook.
# macOS bash 3.2 compatible (no mapfile, no associative arrays).
#
# CONTEXT BUDGET (Anthropic progressive-disclosure practice):
#   Only files that MUST govern every turn are @import'd (resident base context).
#   Everything else is listed as an on-demand pointer the model Reads when relevant.
#   Resident set is driven by the workspace's own steering `inclusion:` metadata:
#     inclusion: always  (or no field) -> RESIDENT (@import)
#     inclusion: auto|fileMatch|manual -> ON-DEMAND (pointer only)
#   All docs/*.md and heavy top-level docs are ON-DEMAND regardless.
#   This keeps the base lean (~10-15k tokens) so the 1M window and every
#   dispatched subagent have room, and autocompact does not thrash.

set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "$0")/.." && pwd)}"
TARGET="${PROJECT_DIR}/CLAUDE.md"
MARKER="<!-- auto-generated by discover-context -->"

# --- Helpers ---------------------------------------------------------------

# Read the `inclusion:` value from a steering file's YAML frontmatter.
# Prints the value (always|auto|fileMatch|manual) or empty if absent.
inclusion_of() {
  local f="$1"
  # Only look inside the leading --- ... --- frontmatter block.
  awk '
    NR==1 && $0!="---" { exit }
    NR==1 { infm=1; next }
    infm && $0=="---" { exit }
    infm && $0 ~ /^inclusion:/ {
      sub(/^inclusion:[[:space:]]*/, "");
      gsub(/[[:space:]]/, "");
      print; exit
    }
  ' "$f" 2>/dev/null
}

# Resident set (@import) and on-demand set (pointer) as plain indexed arrays.
resident_count=0
ondemand_count=0

add_resident() { resident[$resident_count]="$1"; resident_count=$((resident_count + 1)); }
add_ondemand() { ondemand[$ondemand_count]="$1"; ondemand_count=$((ondemand_count + 1)); }

# Classify a steering file by its inclusion mode.
classify_steering() {
  local f="$1"
  [ -f "$f" ] || return 0
  local mode; mode="$(inclusion_of "$f")"
  case "$mode" in
    always|"") add_resident "$f" ;;   # always, or no frontmatter field -> resident
    *)         add_ondemand "$f" ;;   # auto|fileMatch|manual -> on-demand
  esac
}

# --- Steering files: classify each by inclusion metadata --------------------
for f in "${PROJECT_DIR}"/.kiro/steering/*.md; do
  [ -f "$f" ] && classify_steering "$f"
done
if [ -d "${PROJECT_DIR}/.kiro/steering/evolved" ]; then
  for f in "${PROJECT_DIR}"/.kiro/steering/evolved/*.md; do
    [ -f "$f" ] && classify_steering "$f"
  done
fi

# --- docs/*.md and heavy top-level docs: always ON-DEMAND -------------------
for f in "${PROJECT_DIR}"/docs/*.md; do
  [ -f "$f" ] && add_ondemand "$f"
done
for f in ARCHITECTURE.md README.md WORKFLOW_GUIDE.md case_context_database.md; do
  [ -f "${PROJECT_DIR}/${f}" ] && add_ondemand "${PROJECT_DIR}/${f}"
done

# --- Conditional: active space files when RA_ACTIVE_SPACE is set ------------
# Persona/prompts/schema for the active space are small and govern that
# session's behavior, so they are resident when a space is active.
if [ -n "${RA_ACTIVE_SPACE:-}" ]; then
  SPACE_DIR="${PROJECT_DIR}/src/research_assistant/spaces/${RA_ACTIVE_SPACE}"
  if [ -d "$SPACE_DIR" ]; then
    for f in persona.yaml prompts.yaml wiki/_schema.md wiki/_index.md; do
      [ -f "${SPACE_DIR}/${f}" ] && add_resident "${SPACE_DIR}/${f}"
    done
  fi
fi

# Exit early if nothing found
if [ "$resident_count" -eq 0 ] && [ "$ondemand_count" -eq 0 ]; then
  exit 0
fi

# --- First-line comment of a file, for the on-demand pointer description -----
# Uses the first markdown heading or non-empty prose line, trimmed.
describe() {
  local f="$1"
  awk '
    /^---$/ { fm = !fm; next }
    fm { next }
    /^#/ { sub(/^#+[[:space:]]*/, ""); print; exit }
    NF { print; exit }
  ' "$f" 2>/dev/null | cut -c1-90
}

# --- Compose CLAUDE.md body -------------------------------------------------
compose_body() {
  echo "$MARKER"
  echo ""
  echo "# Workspace Context"
  echo ""
  echo "Always-loaded behavioral rules are imported below. Heavy reference"
  echo "material is listed under \"On-demand references\" — Read those files with"
  echo "the Read tool when a task touches them (progressive disclosure keeps the"
  echo "base context lean so the 1M window and dispatched subagents have room)."
  echo ""
  echo "## Always-loaded rules"
  echo ""
  local i=0
  while [ "$i" -lt "$resident_count" ]; do
    echo "@${resident[$i]#"${PROJECT_DIR}"/}"
    i=$((i + 1))
  done
  echo ""
  echo "## On-demand references (Read when relevant — NOT auto-loaded)"
  echo ""
  i=0
  while [ "$i" -lt "$ondemand_count" ]; do
    local rel desc
    rel="${ondemand[$i]#"${PROJECT_DIR}"/}"
    desc="$(describe "${ondemand[$i]}")"
    if [ -n "$desc" ]; then
      echo "- \`${rel}\` — ${desc}"
    else
      echo "- \`${rel}\`"
    fi
    i=$((i + 1))
  done
}

# --- Write or update CLAUDE.md ----------------------------------------------
if [ -f "$TARGET" ] && ! grep -q "^${MARKER}$" "$TARGET" 2>/dev/null; then
  # Hand-maintained CLAUDE.md (no marker): do not clobber. Append only missing
  # resident @import lines, matching the prior script's conservative behavior.
  i=0
  while [ "$i" -lt "$resident_count" ]; do
    line="@${resident[$i]#"${PROJECT_DIR}"/}"
    if ! grep -qF "$line" "$TARGET" 2>/dev/null; then
      echo "$line" >> "$TARGET"
    fi
    i=$((i + 1))
  done
else
  # Auto-generated (marker present or file absent): write fresh.
  compose_body > "$TARGET"
fi

# --- Warn-only guardrail ----------------------------------------------------
# Surface (never block) context-management regressions at session start. Output
# stays tiny to respect the SessionStart hook output cap and avoid re-bloating
# context. Only the one-line verdict is emitted on violation; silent on green.
if [ -x "${PROJECT_DIR}/scripts/harness-doctor.sh" ]; then
  if ! doctor_out="$(bash "${PROJECT_DIR}/scripts/harness-doctor.sh" 2>/dev/null)"; then
    echo "[harness-doctor] WARNING: context-management invariant violated. Run: bash scripts/harness-doctor.sh"
    # Emit only the FAIL lines (compact), not the full report.
    printf '%s\n' "$doctor_out" | grep -i "FAIL" | sed 's/^/  /' | head -5
  fi
fi
