#!/usr/bin/env bash
# harness-doctor.sh — Context-management invariant checker.
#
# Asserts the three properties that keep this workspace aligned with Anthropic's
# documented context model, so a regression can't ship silently:
#   1. MODEL:   no dispatch script passes a non-1M --model (would drop subagents
#               to 200k and cause "Prompt is too long").
#   2. BASE:    CLAUDE.md resident @import bytes stay under budget (lean base;
#               heavy docs must be on-demand, not @import'd).
#   3. MARKER:  CLAUDE.md carries the auto-gen marker (discover-claude-context.sh
#               owns it; a hand-edit that drops the marker would silently re-bloat).
#   4. TREE:    no script/agent references the legacy spaces/*/wiki tree (canonical
#               is src/research_assistant/spaces/*/wiki; a bare ref reads nothing).
#
# Read-only. Exit 0 = all green. Exit 1 = one or more violations.
# Runnable any time in-shell; no fresh session or live subagent required.
# macOS bash 3.2 compatible.

set -uo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "$0")/.." && pwd)}"
CLAUDE_MD="${PROJECT_DIR}/CLAUDE.md"
SCRIPTS_DIR="${PROJECT_DIR}/scripts"

# Budget for resident @import bytes. ~60k chars ≈ 15k tokens: generous headroom
# over the ~40k the always-inclusion rule set currently occupies, but far below
# the pre-fix ~565k. Override via RA_BASE_BUDGET_BYTES.
BASE_BUDGET_BYTES="${RA_BASE_BUDGET_BYTES:-60000}"

fail=0
pass_line() { printf "  \033[32mPASS\033[0m  %s\n" "$1"; }
fail_line() { printf "  \033[31mFAIL\033[0m  %s\n" "$1"; fail=1; }
warn_line() { printf "  \033[33mWARN\033[0m  %s\n" "$1"; }

echo "== harness-doctor: context-management invariants =="
echo ""

# --- Check 1: no dispatch script passes a non-[1m] --model ------------------
echo "1. Dispatch model (must be 1M everywhere):"
# Real (non-comment) --model lines that name a model NOT ending in [1m], and are
# not the RA_AGENT_MODEL variable or the intentional sonnet eval caller.
offenders="$(grep -rn -- '--model ' "$SCRIPTS_DIR" 2>/dev/null \
  | grep -vE '#' \
  | grep -vE 'RA_AGENT_MODEL' \
  | grep -vE '1m\]' \
  | grep -vE 'llm_eval_caller|--model sonnet' \
  | grep -vE 'harness-doctor\.sh' \
  || true)"
if [ -n "$offenders" ]; then
  fail_line "dispatch script(s) pass a non-1M --model:"
  printf '%s\n' "$offenders" | sed 's/^/         /'
else
  pass_line "all dispatch --model flags use RA_AGENT_MODEL / a [1m] variant (sonnet eval caller exempt)"
fi
echo ""

# --- Check 2: resident @import bytes under budget ---------------------------
echo "2. Base context budget (resident @import bytes < ${BASE_BUDGET_BYTES}):"
if [ ! -f "$CLAUDE_MD" ]; then
  warn_line "CLAUDE.md not found (will be generated at next SessionStart)"
else
  total=0; missing=0
  while IFS= read -r line; do
    p="${PROJECT_DIR}/${line#@}"
    if [ -f "$p" ]; then
      b=$(wc -c < "$p" | tr -d ' '); total=$((total + b))
    else
      missing=$((missing + 1))
    fi
  done < <(grep '^@' "$CLAUDE_MD" 2>/dev/null)
  if [ "$total" -gt "$BASE_BUDGET_BYTES" ]; then
    fail_line "resident @import bytes = ${total} exceeds budget ${BASE_BUDGET_BYTES} (heavy docs should be on-demand, not @import'd)"
  else
    pass_line "resident @import bytes = ${total} (budget ${BASE_BUDGET_BYTES})"
  fi
  [ "$missing" -gt 0 ] && warn_line "${missing} @import path(s) point to missing files"
fi
echo ""

# --- Check 3: CLAUDE.md marker present (discover script owns the file) -------
echo "3. CLAUDE.md auto-gen marker (discover-claude-context.sh owns it):"
if [ ! -f "$CLAUDE_MD" ]; then
  warn_line "CLAUDE.md not found"
elif grep -q '^<!-- auto-generated by discover-context -->$' "$CLAUDE_MD" 2>/dev/null; then
  pass_line "marker present — regeneration will keep base lean"
else
  warn_line "no auto-gen marker — CLAUDE.md is hand-maintained; discover script will only append, not slim"
fi
echo ""

# --- Check 4: no operational reference to the legacy wiki tree --------------
# After the Kiro→CC migration (Wave 5, 2026-07-27), the canonical tree is
# src/research_assistant/spaces/*/wiki. A bare "spaces/*/wiki" operational path
# points at the deleted legacy tree and silently reads/writes nothing. Citation
# examples ([spaces/{SPACE}/knowledge/...]) match no-assumption-rule.md and are
# allowed; only executable path references are offenders.
echo "4. No legacy wiki-tree references (canonical is src/research_assistant/spaces):"
# Match "spaces/<SPACE>/wiki" NOT preceded by "research_assistant/" (PCRE negative
# lookbehind), so canonical src/research_assistant/spaces/*/wiki never matches.
# Scan scripts and agent defs; skip this file and comment lines.
legacy="$(grep -rnP '(?<!research_assistant/)spaces/[A-Za-z*{][^ ]*/wiki' \
  "$SCRIPTS_DIR" "${PROJECT_DIR}/.claude/agents" 2>/dev/null \
  | grep -vE 'harness-doctor\.sh' \
  | grep -vE '^[^:]*:[0-9]+:\s*#' \
  || true)"
if [ -n "$legacy" ]; then
  fail_line "operational reference(s) to the legacy spaces/*/wiki tree:"
  printf '%s\n' "$legacy" | sed 's/^/         /'
else
  pass_line "no script/agent references the legacy wiki tree"
fi
echo ""

# --- Summary ----------------------------------------------------------------
if [ "$fail" -eq 0 ]; then
  echo "== harness-doctor: ALL GREEN =="
else
  echo "== harness-doctor: VIOLATIONS FOUND (see FAIL lines above) =="
fi
exit "$fail"
