#!/usr/bin/env python3
"""
obsidian-graph-linker.py
Deterministic wikilink generator for Obsidian graph connectivity.

Reads wiki page frontmatter, resolves relational fields to real files,
and appends a sentinel-wrapped Related block with path-qualified wikilinks.

Usage:
    python3 scripts/obsidian-graph-linker.py             # write links
    python3 scripts/obsidian-graph-linker.py --dry-run   # preview only
    python3 scripts/obsidian-graph-linker.py --check     # verify idempotency
"""

import os
import sys
import re
import argparse
from pathlib import Path

WORKSPACE_ROOT = Path(__file__).resolve().parent.parent

SENTINEL_START = "<!-- OBSIDIAN-LINKS:START (auto-generated by scripts/obsidian-graph-linker.py, do not edit by hand) -->"
SENTINEL_END = "<!-- OBSIDIAN-LINKS:END -->"

WIKI_TREES = [
    WORKSPACE_ROOT / "src" / "research_assistant" / "spaces" / "QNTR" / "wiki",
    WORKSPACE_ROOT / "src" / "research_assistant" / "spaces" / "CRO" / "wiki",
    WORKSPACE_ROOT / "src" / "research_assistant" / "spaces" / "DBA" / "wiki",
    WORKSPACE_ROOT / "src" / "research_assistant" / "spaces" / "CW" / "wiki",
    WORKSPACE_ROOT / "data" / "wiki" / "shared",
]

COMMUNICATION_TREES = [
    WORKSPACE_ROOT / "src" / "research_assistant" / "spaces" / "QNTR" / "communication",
    WORKSPACE_ROOT / "src" / "research_assistant" / "spaces" / "QNTR" / "feedback",
    WORKSPACE_ROOT / "src" / "research_assistant" / "spaces" / "CRO" / "communication",
    WORKSPACE_ROOT / "src" / "research_assistant" / "spaces" / "CRO" / "feedback",
    WORKSPACE_ROOT / "src" / "research_assistant" / "spaces" / "DBA" / "communication",
    WORKSPACE_ROOT / "src" / "research_assistant" / "spaces" / "DBA" / "feedback",
    WORKSPACE_ROOT / "src" / "research_assistant" / "spaces" / "CW" / "communication",
]

RELATIONAL_FIELDS = [
    "sources",
    "draws_from",
    "first_seen",
    "related",
    "mentions_in_sources",
    "mentions_in_syntheses",
    "mentions_in_communications",
    "cross_space_presence",
    "superseded_by",
    "propositions_supported",
]


def parse_frontmatter(filepath):
    """Parse YAML frontmatter from a markdown file. Returns dict or None."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
    except (OSError, UnicodeDecodeError):
        return None

    if not content.startswith("---"):
        return None

    end_idx = content.find("\n---", 3)
    if end_idx == -1:
        return None

    fm_text = content[4:end_idx]
    return parse_yaml_simple(fm_text)


def parse_yaml_simple(text):
    """Minimal YAML parser for frontmatter (handles strings, lists, dicts)."""
    result = {}
    lines = text.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip() or line.strip().startswith("#"):
            i += 1
            continue

        match = re.match(r'^(\w[\w_-]*)\s*:\s*(.*)', line)
        if not match:
            i += 1
            continue

        key = match.group(1)
        value_part = match.group(2).strip()

        if value_part == "" or value_part == "[]":
            # Check if next lines are indented list items or dict entries
            items = []
            j = i + 1
            while j < len(lines):
                next_line = lines[j]
                if next_line.startswith("  - ") or next_line.startswith("    - "):
                    item_val = next_line.strip().lstrip("- ").strip()
                    item_val = item_val.strip('"').strip("'")
                    items.append(item_val)
                    j += 1
                elif next_line.startswith("  ") and ":" in next_line and not next_line.strip().startswith("-"):
                    # Nested dict
                    sub_dict = {}
                    while j < len(lines) and lines[j].startswith("  ") and not lines[j].startswith("  -"):
                        sub_line = lines[j].strip()
                        sub_match = re.match(r'^(\w[\w_-]*)\s*:\s*(.*)', sub_line)
                        if sub_match:
                            sk = sub_match.group(1)
                            sv = sub_match.group(2).strip().strip('"').strip("'")
                            if sv == "" or sv == "[]":
                                sub_items = []
                                j += 1
                                while j < len(lines) and (lines[j].startswith("    -") or lines[j].startswith("      -")):
                                    si = lines[j].strip().lstrip("- ").strip().strip('"').strip("'")
                                    sub_items.append(si)
                                    j += 1
                                sub_dict[sk] = sub_items
                                continue
                            else:
                                sub_dict[sk] = sv
                        j += 1
                    if sub_dict:
                        result[key] = sub_dict
                        i = j
                        continue
                    else:
                        break
                else:
                    break
            if items:
                result[key] = items
            elif key not in result:
                result[key] = value_part if value_part != "[]" else []
            i = j
            continue
        elif value_part.startswith("[") and value_part.endswith("]"):
            inner = value_part[1:-1]
            if inner.strip() == "":
                result[key] = []
            else:
                items = [x.strip().strip('"').strip("'") for x in inner.split(",")]
                result[key] = items
        else:
            result[key] = value_part.strip('"').strip("'")

        i += 1

    return result


def build_resolution_index():
    """Build a mapping of slug patterns to absolute file paths."""
    index = {}

    def determine_space(filepath):
        fp = str(filepath)
        for space in ["QNTR", "CRO", "DBA", "CW"]:
            if f"/spaces/{space}/" in fp:
                return space
        if "/data/wiki/shared" in fp:
            return "shared"
        return "unknown"

    all_files = []

    for tree in WIKI_TREES:
        if tree.exists():
            for md_file in tree.rglob("*.md"):
                if md_file.name.startswith("_"):
                    continue
                abs_path = md_file.resolve()
                space = determine_space(abs_path)
                vault_rel = str(abs_path.relative_to(WORKSPACE_ROOT))
                all_files.append((abs_path, vault_rel, space))

    for tree in COMMUNICATION_TREES:
        if tree.exists():
            for md_file in tree.rglob("*.md"):
                abs_path = md_file.resolve()
                space = determine_space(abs_path)
                vault_rel = str(abs_path.relative_to(WORKSPACE_ROOT))
                all_files.append((abs_path, vault_rel, space))

    # Build multiple lookup keys for each file
    for abs_path, vault_rel, space in all_files:
        stem = abs_path.stem
        parent_name = abs_path.parent.name

        # Key patterns to register:
        # 1. Full vault-relative path (with and without .md)
        index.setdefault(vault_rel, []).append((abs_path, vault_rel, space))
        index.setdefault(vault_rel.replace(".md", ""), []).append((abs_path, vault_rel, space))

        # 2. Relative from wiki root: e.g. "sources/berente-2021-managing-ai"
        # Determine the wiki root for this file
        wiki_rel = _compute_wiki_relative(abs_path, space)
        if wiki_rel:
            index.setdefault(wiki_rel, []).append((abs_path, vault_rel, space))
            index.setdefault(wiki_rel + ".md", []).append((abs_path, vault_rel, space))

        # 3. "wiki/" prefixed variant: "wiki/sources/berente-2021"
        if wiki_rel:
            wiki_prefixed = "wiki/" + wiki_rel
            index.setdefault(wiki_prefixed, []).append((abs_path, vault_rel, space))
            index.setdefault(wiki_prefixed + ".md", []).append((abs_path, vault_rel, space))

        # 4. "spaces/SPACE/wiki/..." prefixed
        if space not in ("shared", "unknown"):
            spaces_prefixed = f"spaces/{space}/wiki/{wiki_rel}" if wiki_rel else None
            if spaces_prefixed:
                index.setdefault(spaces_prefixed, []).append((abs_path, vault_rel, space))
                index.setdefault(spaces_prefixed + ".md", []).append((abs_path, vault_rel, space))

        # 5. Communication/feedback relative paths: "communication/filename"
        comm_rel = _compute_comm_relative(abs_path, space)
        if comm_rel:
            index.setdefault(comm_rel, []).append((abs_path, vault_rel, space))
            index.setdefault(comm_rel + ".md", []).append((abs_path, vault_rel, space))

        # 6. Bare stem (lowest priority, ambiguous)
        index.setdefault(stem, []).append((abs_path, vault_rel, space))

    return index, all_files


def _compute_wiki_relative(abs_path, space):
    """Compute the path relative to the wiki root (e.g. sources/berente-2021-managing-ai)."""
    fp = str(abs_path)
    markers = [
        f"/spaces/{space}/wiki/",
        "/data/wiki/shared/",
    ]
    for marker in markers:
        idx = fp.find(marker)
        if idx != -1:
            rel = fp[idx + len(marker):]
            if rel.endswith(".md"):
                rel = rel[:-3]
            return rel
    return None


def _compute_comm_relative(abs_path, space):
    """Compute path relative to space root for communication/feedback files."""
    fp = str(abs_path)
    for kind in ("communication", "feedback"):
        marker = f"/spaces/{space}/{kind}/"
        idx = fp.find(marker)
        if idx != -1:
            rel = f"{kind}/{abs_path.stem}"
            return rel
    return None


def resolve_slug(slug, index, source_space):
    """Resolve a frontmatter slug to a vault-relative path. Returns (vault_rel, resolved) or (None, False)."""
    if not slug or not isinstance(slug, str):
        return None, False

    slug = slug.strip().strip('"').strip("'")
    if not slug:
        return None, False

    candidates = index.get(slug, [])
    if not candidates:
        # Try stripping leading .md or adding it
        alt = slug[:-3] if slug.endswith(".md") else slug + ".md"
        candidates = index.get(alt, [])

    if not candidates:
        # Try stripping "spaces/SPACE/wiki/" prefix variants
        for prefix in [f"spaces/{source_space}/wiki/", "spaces/QNTR/wiki/", "spaces/CRO/wiki/",
                       "spaces/DBA/wiki/", "spaces/CW/wiki/"]:
            if slug.startswith(prefix):
                remainder = slug[len(prefix):]
                candidates = index.get(remainder, [])
                if candidates:
                    break
                candidates = index.get(remainder.rstrip(".md"), [])
                if candidates:
                    break

    if not candidates:
        return None, False

    # Prefer same-space match
    same_space = [c for c in candidates if c[2] == source_space]
    if same_space:
        return same_space[0][1], True

    # Then shared
    shared = [c for c in candidates if c[2] == "shared"]
    if shared:
        return shared[0][1], True

    # First match
    return candidates[0][1], True


def extract_relational_slugs(frontmatter):
    """Extract all relational slugs from frontmatter, grouped by field name."""
    relations = {}

    for field in RELATIONAL_FIELDS:
        if field not in frontmatter:
            continue

        value = frontmatter[field]

        if field == "cross_space_presence":
            # This is a list of dicts with space/present/reason; skip (no file targets)
            continue

        if field == "propositions_supported":
            # These are proposition labels (P1, P2), not file references
            continue

        slugs = []
        if isinstance(value, str):
            slugs = [value]
        elif isinstance(value, list):
            for item in value:
                if isinstance(item, str):
                    slugs.append(item)
        elif isinstance(value, dict):
            # draws_from can be {QNTR: [...], shared: [...]}
            for k, v in value.items():
                if isinstance(v, list):
                    for item in v:
                        if isinstance(item, str):
                            slugs.append(item)
                elif isinstance(v, str):
                    slugs.append(v)

        # Filter out entries that are nested dict remnants from source-type pages
        # (e.g. 'path: "data/summaries/..."' parsed from YAML dicts with path/type keys)
        # Also filter raw source material paths (PDFs, DOCX, PPTX, XLSX, .eml, output/ dirs)
        filtered = []
        for slug in slugs:
            if slug.startswith("path:"):
                continue
            if slug.startswith("type:"):
                continue
            # Skip references to non-wiki raw files
            ext_match = re.search(r'\.(pdf|docx|pptx|xlsx|sav|eml)$', slug, re.IGNORECASE)
            if ext_match:
                continue
            # Skip output/ and knowledge/ paths that are not wiki pages
            if "/output/" in slug or slug.startswith("output/"):
                continue
            if "/knowledge/" in slug or slug.startswith("knowledge/"):
                continue
            filtered.append(slug)

        if filtered:
            relations[field] = filtered

    return relations


def make_wikilink(vault_rel_path):
    """Create a path-qualified Obsidian wikilink from a vault-relative path."""
    # Strip .md for Obsidian convention
    display = vault_rel_path
    if display.endswith(".md"):
        display = display[:-3]

    # Alias is just the filename stem
    alias = Path(vault_rel_path).stem

    return f"[[{display}|{alias}]]"


FIELD_DISPLAY_NAMES = {
    "sources": "Sources",
    "draws_from": "Draws from",
    "first_seen": "First seen",
    "related": "Related",
    "mentions_in_sources": "Mentioned in sources",
    "mentions_in_syntheses": "Mentioned in syntheses",
    "mentions_in_communications": "Mentioned in communications",
    "superseded_by": "Superseded by",
}


def build_link_block(resolved_relations):
    """Build the sentinel-wrapped link block to append."""
    lines = []
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(SENTINEL_START)
    lines.append("## Related")

    for field, links in sorted(resolved_relations.items(), key=lambda x: x[0]):
        display_name = FIELD_DISPLAY_NAMES.get(field, field.replace("_", " ").title())
        sorted_links = sorted(links)
        links_str = " , ".join(sorted_links)
        lines.append(f"- **{display_name}**: {links_str}")

    lines.append(SENTINEL_END)
    lines.append("")

    return "\n".join(lines)


def strip_existing_block(content):
    """Remove any existing sentinel block from content."""
    start_idx = content.find(SENTINEL_START)
    if start_idx == -1:
        return content

    end_idx = content.find(SENTINEL_END, start_idx)
    if end_idx == -1:
        return content

    end_idx += len(SENTINEL_END)
    # Also strip trailing newline after END
    if end_idx < len(content) and content[end_idx] == "\n":
        end_idx += 1

    # Also strip the preceding horizontal rule and blank lines if they are part of our block
    # Look backwards from start_idx for "\n---\n\n" pattern
    pre_start = start_idx
    check_area = content[max(0, pre_start - 10):pre_start]
    if check_area.rstrip().endswith("---"):
        # Find the --- line
        rule_idx = content.rfind("\n---", 0, pre_start)
        if rule_idx != -1:
            # Check there is at most a blank line between --- and sentinel
            between = content[rule_idx:pre_start]
            if between.strip() == "---":
                pre_start = rule_idx
                # Also strip one preceding newline
                if pre_start > 0 and content[pre_start - 1] == "\n":
                    pre_start -= 1

    return content[:pre_start] + content[end_idx:]


def process_file(filepath, index, dry_run=False):
    """Process a single wiki file. Returns (links_added, unresolved_list)."""
    fm = parse_frontmatter(filepath)
    if not fm:
        return 0, []

    abs_path = Path(filepath).resolve()
    fp_str = str(abs_path)

    # Determine source space
    source_space = "unknown"
    for space in ["QNTR", "CRO", "DBA", "CW"]:
        if f"/spaces/{space}/" in fp_str:
            source_space = space
            break
    if "/data/wiki/shared" in fp_str:
        source_space = "shared"

    relations = extract_relational_slugs(fm)
    if not relations:
        return 0, []

    resolved_relations = {}
    unresolved = []
    total_links = 0

    for field, slugs in relations.items():
        field_links = []
        for slug in slugs:
            vault_rel, ok = resolve_slug(slug, index, source_space)
            if ok:
                # Do not link to self
                if vault_rel and str(abs_path) != str((WORKSPACE_ROOT / vault_rel).resolve()):
                    link = make_wikilink(vault_rel)
                    if link not in field_links:
                        field_links.append(link)
                        total_links += 1
            else:
                unresolved.append((str(abs_path.relative_to(WORKSPACE_ROOT)), field, slug))

        if field_links:
            resolved_relations[field] = field_links

    if not resolved_relations:
        return 0, unresolved

    if dry_run:
        return total_links, unresolved

    # Read file, strip old block, append new block
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    content = strip_existing_block(content)

    # Ensure content ends with a newline before appending
    if not content.endswith("\n"):
        content += "\n"

    block = build_link_block(resolved_relations)
    content += block

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

    return total_links, unresolved


def get_wiki_pages():
    """Get all wiki page paths (excluding _index, _log, _schema, learner files)."""
    pages = []
    for tree in WIKI_TREES:
        if not tree.exists():
            continue
        for md_file in tree.rglob("*.md"):
            if md_file.name.startswith("_"):
                continue
            # Skip learner pattern files (different structure)
            if "/learner/" in str(md_file):
                continue
            pages.append(md_file.resolve())
    return sorted(pages)


def main():
    parser = argparse.ArgumentParser(description="Generate Obsidian wikilinks from wiki frontmatter")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without writing")
    parser.add_argument("--check", action="store_true", help="Verify idempotency (running twice produces no diff)")
    args = parser.parse_args()

    print(f"Workspace root: {WORKSPACE_ROOT}")
    print("Building resolution index...")
    index, all_files = build_resolution_index()
    print(f"  Indexed {len(all_files)} files across wiki + communication + feedback trees")

    pages = get_wiki_pages()
    print(f"  Found {len(pages)} wiki pages to process")

    if args.check:
        # Run the process and check if any file would change
        print("\nRunning idempotency check...")
        changes_needed = 0
        for page in pages:
            with open(page, "r", encoding="utf-8") as f:
                before = f.read()

            links, _ = process_file(page, index, dry_run=False)

            with open(page, "r", encoding="utf-8") as f:
                after = f.read()

            if before != after:
                changes_needed += 1
                # Restore original
                with open(page, "w", encoding="utf-8") as f:
                    f.write(before)

        if changes_needed == 0:
            print("PASS: No changes needed. Script is idempotent.")
            sys.exit(0)
        else:
            print(f"FAIL: {changes_needed} file(s) would change on re-run.")
            sys.exit(1)

    total_links = 0
    total_unresolved = []
    files_modified = 0
    links_by_field = {}

    mode = "DRY RUN" if args.dry_run else "WRITE"
    print(f"\nProcessing pages ({mode})...")

    for page in pages:
        links, unresolved = process_file(page, index, dry_run=args.dry_run)
        if links > 0:
            files_modified += 1
            total_links += links
        total_unresolved.extend(unresolved)

        # Track per-field counts
        fm = parse_frontmatter(page)
        if fm:
            source_space = "unknown"
            for space in ["QNTR", "CRO", "DBA", "CW"]:
                if f"/spaces/{space}/" in str(page):
                    source_space = space
                    break
            if "/data/wiki/shared" in str(page):
                source_space = "shared"
            relations = extract_relational_slugs(fm)
            for field, slugs in relations.items():
                for slug in slugs:
                    vault_rel, ok = resolve_slug(slug, index, source_space)
                    if ok:
                        links_by_field[field] = links_by_field.get(field, 0) + 1

    print(f"\nResults:")
    print(f"  Files processed: {len(pages)}")
    print(f"  Files with links: {files_modified}")
    print(f"  Total links generated: {total_links}")
    print(f"  Unresolved references: {len(total_unresolved)}")

    if links_by_field:
        print(f"\n  Links by relation type:")
        for field in sorted(links_by_field.keys()):
            print(f"    {field}: {links_by_field[field]}")

    # Write unresolved report
    report_path = WORKSPACE_ROOT / "data" / "logs" / "obsidian-linker-report.md"
    report_path.parent.mkdir(parents=True, exist_ok=True)

    with open(report_path, "w", encoding="utf-8") as f:
        f.write("# Obsidian Graph Linker: Unresolved References\n\n")
        f.write(f"Generated: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n")
        if total_unresolved:
            f.write(f"Total unresolved: {len(total_unresolved)}\n\n")
            f.write("| Source File | Field | Unresolved Slug |\n")
            f.write("|---|---|---|\n")
            for src, field, slug in sorted(total_unresolved):
                f.write(f"| {src} | {field} | `{slug}` |\n")
        else:
            f.write("All references resolved successfully.\n")

    print(f"\n  Report written to: {report_path.relative_to(WORKSPACE_ROOT)}")

    if args.dry_run:
        print("\n  (Dry run: no files were modified)")


if __name__ == "__main__":
    main()
